### ISSUE TITLE
Version 3.1.0 is not published to npm

### ISSUE THREAD

**Issue by LinusU** [toddbluhm/ts-standard#13]
There seems be a new version, 3.1.0, in the `master` branch, but this version is not published to npm.

The current version gives this warning when trying to use it with TypeScript 3.7 so would appreciate if you could publish the 3.1.0 version ☺️ 

> npm WARN ts-standard@3.0.0 requires a peer of typescript@>=3.0.0 <3.7.0 but none is installed.

**Comment by toddbluhm** [comment]
I apologize for that. It should be published now. I also amended the Typescript restriction to simply require any version 3.x.
