### ISSUE TITLE
How to use ts-standard inside VS Code?

### ISSUE THREAD

**Issue by nebiros** [toddbluhm/ts-standard#32]
First, thank you, works great!, but, how to use ts-standard inside VS Code?, there's some way to use the [vscode-standardjs ext](https://marketplace.visualstudio.com/items?itemName=chenxsan.vscode-standardjs) with this package?

Thank you

**Comment by toddbluhm** [comment]
Hey, great question. There is currently a draft PR for that over on the `vscode-standardjs` extension repo here: https://github.com/standard/vscode-standardjs/pull/103

Feel free to pull down that PR, build the extension, and try it out for yourself. That PR is compatible with `ts-standard@8.0.0` and above

**Comment by nebiros** [comment]
Works awesome!, thank you

**Comment by toddbluhm** [comment]
@nebiros Awesome!!! Thank you for testing it out! If you run into any issues with it, please feel free to let me know either here or in that `vscode-standardjs` PR 😄

**Comment by toddbluhm** [comment]
The PR implementing `ts-standard` into the `vscode-standardjs` extension has been merge and the updated version of the extension has been released.

**Comment by microhobby** [comment]
sorry if i didn't get it how to make this work, I installed the extension and added `ts-standard` to my `package.json` but I have the following output:

```
To use JavaScript Standard Style please install JavaScript Standard Style by running 'npm install standard' in the workspace folder torizon
or globally using 'npm install -g standard'. You need to reopen the workspace after installing JavaScript Standard Style.

Alternatively you can disable JavaScript Standard Style for the workspace folder torizon by executing the 'Disable JavaScript Standard Style' command.
```

What am I missing here? I have to add the `standard` too (I tested it but it now seems to only lint JS files)

**Comment by microhobby** [comment]
Ok, adding `"standard.engine": "ts-standard"` to my `settings.json` make it work.
RTFM right 😂.

Thanks for the great job

**Comment by n1kk** [comment]
Also seems to require latest version of the package, I had `^11` but it wasn't working, installed `^12` and it started working. Although, it highlights errors after formatting, guess I have to play some more with settings and configs. No so much zero config after all.
