### ISSUE TITLE
Parser defined in config

### ISSUE THREAD

**Issue by mightyiam** [toddbluhm/ts-standard#9]
https://github.com/toddbluhm/ts-standard/blob/dd59e4a99690c866d0017dd68d00c6d4800bcfbb/eslintrc.json#L3

This line is no longer necessary.

**Comment by mightyiam** [comment]
Nor is this:
https://github.com/toddbluhm/ts-standard/blob/dd59e4a99690c866d0017dd68d00c6d4800bcfbb/package.json#L28

**Comment by toddbluhm** [comment]
Thanks!!! This has been fixed in commit: https://github.com/toddbluhm/ts-standard/commit/e85823284b5e7fa07dff1416c5d2d551301891d1
